package com.zz.recycleviewmvptest.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zz.recycleviewmvptest.bean.ChatBean;
import com.zz.recycleviewmvptest.bean.ChessListBean;
import com.zz.recycleviewmvptest.bean.MyInfoBean;
import com.zz.recycleviewmvptest.bean.UserInfoBean;

import com.zz.recycleviewmvptest.bean.ChatBeanDao;
import com.zz.recycleviewmvptest.bean.ChessListBeanDao;
import com.zz.recycleviewmvptest.bean.MyInfoBeanDao;
import com.zz.recycleviewmvptest.bean.UserInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatBeanDaoConfig;
    private final DaoConfig chessListBeanDaoConfig;
    private final DaoConfig myInfoBeanDaoConfig;
    private final DaoConfig userInfoBeanDaoConfig;

    private final ChatBeanDao chatBeanDao;
    private final ChessListBeanDao chessListBeanDao;
    private final MyInfoBeanDao myInfoBeanDao;
    private final UserInfoBeanDao userInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        chessListBeanDaoConfig = daoConfigMap.get(ChessListBeanDao.class).clone();
        chessListBeanDaoConfig.initIdentityScope(type);

        myInfoBeanDaoConfig = daoConfigMap.get(MyInfoBeanDao.class).clone();
        myInfoBeanDaoConfig.initIdentityScope(type);

        userInfoBeanDaoConfig = daoConfigMap.get(UserInfoBeanDao.class).clone();
        userInfoBeanDaoConfig.initIdentityScope(type);

        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);
        chessListBeanDao = new ChessListBeanDao(chessListBeanDaoConfig, this);
        myInfoBeanDao = new MyInfoBeanDao(myInfoBeanDaoConfig, this);
        userInfoBeanDao = new UserInfoBeanDao(userInfoBeanDaoConfig, this);

        registerDao(ChatBean.class, chatBeanDao);
        registerDao(ChessListBean.class, chessListBeanDao);
        registerDao(MyInfoBean.class, myInfoBeanDao);
        registerDao(UserInfoBean.class, userInfoBeanDao);
    }
    
    public void clear() {
        chatBeanDaoConfig.clearIdentityScope();
        chessListBeanDaoConfig.clearIdentityScope();
        myInfoBeanDaoConfig.clearIdentityScope();
        userInfoBeanDaoConfig.clearIdentityScope();
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

    public ChessListBeanDao getChessListBeanDao() {
        return chessListBeanDao;
    }

    public MyInfoBeanDao getMyInfoBeanDao() {
        return myInfoBeanDao;
    }

    public UserInfoBeanDao getUserInfoBeanDao() {
        return userInfoBeanDao;
    }

}
